version: '2'

services:
  dummy-backend:
    build: .
    image: dummy-backend
    environment:
      - SERVER_PORT=:8080
#    ports:
#      - "8080:8080"

  nginx:
    image: nginx:1.21.6
    ports:
      - "5555:80"
    volumes:
      - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - dummy-backend