version: '2'

services:
  dummy-backend:
    build: .
    image: dummy-backend
    environment:
      - SERVER_PORT=:8080
      - MONGO_URL=mongodb://root:example@mongo:27017/
#    ports:
#      - "8080:8080"
    networks:
      - my-network

  nginx:
    image: nginx:1.21.6
    ports:
      - "5555:80"
    volumes:
      - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - my-network

# This is optional, if not specified docker-compose will create automatically a default network between the containers
networks:
  my-network: